openapi: 3.0.3
info:
  title: Softfact API
  description: API para gerenciamento de alunos e projetos da Fabrica de Software Uniesp
  version: 1.0.0
  contact:
    name: Softfact Team
servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: Alunos
    description: Gerenciamento de alunos
  - name: Projetos
    description: Gerenciamento de projetos
  - name: Stacks
    description: Gerenciamento de tecnologias

paths:
  /api/alunos:
    get:
      tags:
        - Alunos
      summary: Listar alunos
      description: Retorna uma lista paginada de alunos
      operationId: listarAlunos
      parameters:
        - name: query
          in: query
          description: Termo de busca
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageAlunoResponse"
    post:
      tags:
        - Alunos
      summary: Criar aluno
      operationId: criarAluno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AlunoCreateRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AlunoResponse"
        "400":
          description: Bad Request

  /api/alunos/{id}:
    get:
      tags:
        - Alunos
      summary: Buscar aluno por ID
      operationId: buscarAluno
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AlunoResponse"
        "404":
          description: Not Found
    put:
      tags:
        - Alunos
      summary: Atualizar aluno
      operationId: atualizarAluno
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AlunoUpdateRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AlunoResponse"
        "404":
          description: Not Found
    delete:
      tags:
        - Alunos
      summary: Excluir aluno
      operationId: excluirAluno
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
        "404":
          description: Not Found

  /api/projetos:
    get:
      tags:
        - Projetos
      summary: Listar projetos
      description: Retorna uma lista paginada de projetos
      operationId: listarProjetos
      parameters:
        - name: termo
          in: query
          required: false
          schema:
            type: string
        - name: semestre
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageProjetoResponse"
    post:
      tags:
        - Projetos
      summary: Criar projeto
      operationId: criarProjeto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjetoCreateRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjetoResponse"
        "400":
          description: Bad Request

  /api/projetos/{id}:
    get:
      tags:
        - Projetos
      summary: Buscar projeto por ID
      operationId: buscarProjeto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjetoResponse"
        "404":
          description: Not Found
    put:
      tags:
        - Projetos
      summary: Atualizar projeto
      operationId: atualizarProjeto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjetoUpdateRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjetoResponse"
        "404":
          description: Not Found
    delete:
      tags:
        - Projetos
      summary: Excluir projeto
      operationId: excluirProjeto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
        "404":
          description: Not Found

  /api/stacks:
    get:
      tags:
        - Stacks
      summary: Listar stacks
      description: Retorna uma lista paginada de tecnologias
      operationId: listarStacks
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageStackResponse"
    post:
      tags:
        - Stacks
      summary: Criar stack
      operationId: criarStack
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StackRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StackResponse"
        "400":
          description: Bad Request

  /api/stacks/{id}:
    get:
      tags:
        - Stacks
      summary: Buscar stack por ID
      operationId: buscarStack
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StackResponse"
        "404":
          description: Not Found
    put:
      tags:
        - Stacks
      summary: Atualizar stack
      operationId: atualizarStack
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StackRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StackResponse"
        "404":
          description: Not Found
    delete:
      tags:
        - Stacks
      summary: Excluir stack
      operationId: excluirStack
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Success
        "404":
          description: Not Found

components:
  schemas:
    AlunoCreateRequest:
      type: object
      required:
        - nome
        - email
        - curso
        - matricula
        - periodo
      properties:
        nome:
          type: string
          example: Joao da Silva
        email:
          type: string
          format: email
          example: joao.silva@aluno.uniesp.edu.br
        telefone:
          type: string
          example: (11) 98765-4321
        curso:
          type: string
          enum:
            - CIENCIA_DA_COMPUTACAO
            - ENGENHARIA_DA_COMPUTACAO
            - SISTEMAS_DE_INFORMACAO
            - ANALISE_E_DESENVOLVIMENTO_DE_SISTEMAS
            - ENGENHARIA_DE_SOFTWARE
          example: CIENCIA_DA_COMPUTACAO
        matricula:
          type: string
          example: "202301234"
        periodo:
          type: string
          enum:
            - P1
            - P2
            - P3
            - P4
            - P5
            - P6
            - P7
            - P8
            - P9
            - P10
          example: P5
        stacksIds:
          type: array
          items:
            type: integer
            format: int64
          example: [1, 2, 5]

    AlunoUpdateRequest:
      type: object
      required:
        - nome
        - email
        - curso
        - matricula
        - periodo
      properties:
        nome:
          type: string
          example: Joao da Silva
        email:
          type: string
          format: email
          example: joao.silva@aluno.uniesp.edu.br
        telefone:
          type: string
          example: (11) 98765-4321
        curso:
          type: string
          enum:
            - CIENCIA_DA_COMPUTACAO
            - ENGENHARIA_DA_COMPUTACAO
            - SISTEMAS_DE_INFORMACAO
            - ANALISE_E_DESENVOLVIMENTO_DE_SISTEMAS
            - ENGENHARIA_DE_SOFTWARE
          example: CIENCIA_DA_COMPUTACAO
        matricula:
          type: string
          example: "202301234"
        periodo:
          type: string
          enum:
            - P1
            - P2
            - P3
            - P4
            - P5
            - P6
            - P7
            - P8
            - P9
            - P10
          example: P5
        stacksIds:
          type: array
          items:
            type: integer
            format: int64
          example: [1, 2, 5]

    AlunoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nome:
          type: string
          example: Joao da Silva
        email:
          type: string
          format: email
          example: joao.silva@aluno.uniesp.edu.br
        telefone:
          type: string
          example: (11) 98765-4321
        curso:
          type: string
          example: CIENCIA_DA_COMPUTACAO
        matricula:
          type: string
          example: "202301234"
        periodo:
          type: string
          example: P5
        stacks:
          type: array
          items:
            $ref: "#/components/schemas/StackResumo"

    ProjetoCreateRequest:
      type: object
      required:
        - nome
        - semestre
        - tipo
        - status
      properties:
        nome:
          type: string
          example: Sistema de Gestao Academica
        descricao:
          type: string
          example: Sistema web para gerenciar matriculas
        semestre:
          type: string
          example: "2025.1"
        tipo:
          type: string
          enum:
            - EMPRESA_PARCEIRA
            - AUTORAL
          example: EMPRESA_PARCEIRA
        nomeEmpresa:
          type: string
          example: Tech Solutions Ltda
        status:
          type: string
          enum:
            - PLANEJADO
            - EM_ANDAMENTO
            - CONCLUIDO
            - CANCELADO
          example: EM_ANDAMENTO
        stacksDesejadas:
          type: array
          items:
            type: integer
            format: int64
          example: [1, 3, 7]
        alunosIds:
          type: array
          items:
            type: integer
            format: int64
          example: [1, 5, 12]

    ProjetoUpdateRequest:
      type: object
      required:
        - nome
        - semestre
        - tipo
        - status
      properties:
        nome:
          type: string
          example: Sistema de Gestao Academica
        descricao:
          type: string
          example: Sistema web para gerenciar matriculas
        semestre:
          type: string
          example: "2025.1"
        tipo:
          type: string
          enum:
            - EMPRESA_PARCEIRA
            - AUTORAL
          example: EMPRESA_PARCEIRA
        nomeEmpresa:
          type: string
          example: Tech Solutions Ltda
        status:
          type: string
          enum:
            - PLANEJADO
            - EM_ANDAMENTO
            - CONCLUIDO
            - CANCELADO
          example: EM_ANDAMENTO
        stacksDesejadas:
          type: array
          items:
            type: integer
            format: int64
          example: [1, 3, 7]
        alunosIds:
          type: array
          items:
            type: integer
            format: int64
          example: [1, 5, 12]

    ProjetoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nome:
          type: string
          example: Sistema de Gestao Academica
        descricao:
          type: string
          example: Sistema web para gerenciar matriculas
        semestre:
          type: string
          example: "2025.1"
        tipo:
          type: string
          example: EMPRESA_PARCEIRA
        nomeEmpresa:
          type: string
          example: Tech Solutions Ltda
        status:
          type: string
          example: EM_ANDAMENTO
        stacksDesejadas:
          type: array
          items:
            $ref: "#/components/schemas/StackResumo"
        alunos:
          type: array
          items:
            $ref: "#/components/schemas/AlunoResponse"

    StackRequest:
      type: object
      required:
        - nome
      properties:
        nome:
          type: string
          example: Java
        categoria:
          type: string
          example: Backend

    StackResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nome:
          type: string
          example: Java
        categoria:
          type: string
          example: Backend

    StackResumo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nome:
          type: string
          example: Java
        categoria:
          type: string
          example: Backend

    PageAlunoResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/AlunoResponse"
        totalElements:
          type: integer
          format: int64
          example: 100
        totalPages:
          type: integer
          example: 5
        size:
          type: integer
          example: 20
        number:
          type: integer
          example: 0

    PageProjetoResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/ProjetoResponse"
        totalElements:
          type: integer
          format: int64
          example: 50
        totalPages:
          type: integer
          example: 3
        size:
          type: integer
          example: 20
        number:
          type: integer
          example: 0

    PageStackResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/StackResponse"
        totalElements:
          type: integer
          format: int64
          example: 10
        totalPages:
          type: integer
          example: 1
        size:
          type: integer
          example: 20
        number:
          type: integer
          example: 0
